### ISSUE TITLE
is humanize rounding correctly?

### ISSUE THREAD

**Issue by mlexs** [jfcalvo/size#5]
trying out the `humanize` function, and it looks like it's broken or perhaps I'm doing something wrong?

```elixir
iex> Size.humanize!(2147483647)
"2 GB"
```

this should return 2.14 GB since the `round` param is default to 2 and 2147483647 bytes is 2.14 GB.

next:
```elixir
iex> Size.humanize!(2147483647, round: 3)
"2 GB"
```

how can I please obtain a correct rounded value?

**Comment by jfcalvo** [comment]
I believe the problem is that you are expecting one gigabyte to be 1000000000 (10^9) bytes but `humanize!` function (and the rest of functions and macros) works with the assumption that one gigabyte is 1073741824 (2^30) bytes.

Take this for example:

```elixir
Size.gigabytes(1)
1073741824
```

Sadly there is not an easy solution apart from upgrading the library to make this distinction between gigabytes and gibibytes, kilobytes and kibibytes, etc.

**Comment by mlexs** [comment]
Thanks for your prompt reply.

I think I got fooled by the fact it returns "GB" and not "GiB" as correct unit symbol.

Yes, it's the Decimal units (10^9) as expected end result for my issue - I'm trying to display storage space to users in my app, and it's preferable to have e.g "2.14 GB" instead of "2 GB".

Here quick example of Python's equivalent library.
```bash
> pip install humanize
> python -c "import humanize; print(humanize.naturalsize(2147483647, binary=True, format='%.2f'))"
2.00 GiB
> python -c "import humanize; print(humanize.naturalsize(2147483647, binary=False, format='%.2f'))"
2.15 GB
```

Seems like `humanize` macro would benefit from `binary: true` option and some underlying macros to support it. Are you planning to add such functionality?

**Comment by jfcalvo** [comment]
Sorry, not for the moment.

**Comment by mlexs** [comment]
That's fine. Thanks for your honestly.

I resolved my issue with [file_size](https://github.com/tlux/file_size) library - I'm not its author - just link for others who might want a library with bit and byte based units.
